# Extra Space
LTO_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 

ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes

CAPS_WORD_ENABLE = yes
TAP_DANCE_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = SSD1306
OCEAN_DREAM_ENABLE = yes # animation
WPM_ENABLE = yes
